name: First Workflow
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
           echo "Hello World!"
           echo "Hello 4"  
      - name: Print goodbye
        run: echo "Done - bye!"

